name: Auto merge main to dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:         
      - 
        name: Merge
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'Bot@nagaseyami.com'

          git pull --unshallow

          git checkout dev
          git merge --no-edit origin/main
          git push origin dev
