name: build-docker-image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - 
        name: Merge
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'Bot@nagaseyami.com'

          git pull --unshallow

          git chekout dev
          git merge --no-edit origin/main
          git push origin dev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: nagaseyami/revanced-builder:latest
